import "~/styles/globals.css";

import { Inter } from "next/font/google";
import { ViewTransitions } from "next-view-transitions";
import { TRPCReactProvider } from "~/trpc/react";
import { ClerkProvider } from "@clerk/nextjs";
import { TopNav } from "./_components/topnav";

import { ruRU } from "@clerk/localizations";

const inter = Inter({
  subsets: ["latin"],
  variable: "--font-sans",
});

export const metadata = {
  title: "Create T3 App",
  description: "Generated by create-t3-app",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <ClerkProvider localization={ruRU}>
      <ViewTransitions>
        <html lang="en">
          <body
            className={`font-sans bg-background ${inter.variable} grid h-screen grid-rows-[auto_1fr]`}
          >
            <TRPCReactProvider>
              <TopNav />
              <main className="overflow-y-scroll">{children}</main>
            </TRPCReactProvider>
          </body>
        </html>
      </ViewTransitions>
    </ClerkProvider>
  );
}
