import "~/styles/globals.css";

import { Inter } from "next/font/google";
import { ViewTransitions } from "next-view-transitions";
import { TRPCReactProvider } from "~/trpc/react";
import { ClerkProvider } from "@clerk/nextjs";
import { TopNav } from "./_components/topnav";

import { ruRU } from "@clerk/localizations";
import Image from "next/image";
import { Toaster } from "~/components/ui/toaster";

const inter = Inter({
  subsets: ["latin"],
  variable: "--font-sans",
});

export const metadata = {
  title: "Create T3 App",
  description: "Generated by create-t3-app",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <ClerkProvider localization={ruRU}>
      <ViewTransitions>
        <html lang="en">
          <body
            className={`font-sans ${inter.variable} grid h-screen grid-rows-[auto_1fr] bg-background`}
          >
            <TRPCReactProvider>
              <TopNav />
              <main className="z-10 overflow-y-scroll">{children}</main>
              <Image
                src="/bg-image.png"
                alt="Background image"
                fill
                className="absolute inset-0 h-full"
                style={{ objectFit: "cover", position: "absolute" }}
              />
              <Toaster />
            </TRPCReactProvider>
          </body>
        </html>
      </ViewTransitions>
    </ClerkProvider>
  );
}
